// Bakes the vendored woff2 into a TS module so the EPUB builder can embed it
// identically in Node (tests, CLI) and in the browser, with no fetch at runtime.
// Run: npm run embed:font
import { readFile, writeFile } from 'node:fs/promises';

const font = await readFile('src/assets/fonts/FrankRuhlLibre-hebrew.woff2');
const license = await readFile('src/assets/fonts/OFL.txt', 'utf8');

await writeFile(
  'src/assets/fonts/frankRuhl.ts',
  `// GENERATED by scripts/embed-font.mjs — do not edit by hand.
// Frank Ruhl Libre, Hebrew subset, variable weight 400-700.
// SIL Open Font License 1.1 — embedding is expressly permitted.
export const FRANK_RUHL_WOFF2_BASE64 =
  '${font.toString('base64')}';

export const FRANK_RUHL_LICENSE = ${JSON.stringify(license)};

/** Decode to bytes for zipping into an EPUB. */
export function frankRuhlBytes(): Uint8Array {
  const bin = atob(FRANK_RUHL_WOFF2_BASE64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}
`,
);
console.log(`Embedded ${font.length} bytes of woff2 (${Math.round((font.length * 4) / 3)} b64)`);
